from dataclasses import dataclass
from typing import List

@dataclass
class DecisionOutput:
    """The structured JSON response generated by the Decision Engine."""
    incident_id: str
    device_type: str
    diagnosis: str
    recommended_actions: List[str]
    confidence: float
    memory_match: bool
    escalate: bool
    escalation_reason: str
    citations: List[str]
    
    def to_dict(self):
        return {
            "incident_id": self.incident_id,
            "device_type": self.device_type,
            "diagnosis": self.diagnosis,
            "recommended_actions": self.recommended_actions,
            "confidence": self.confidence,
            "memory_match": self.memory_match,
            "escalate": self.escalate,
            "escalation_reason": self.escalation_reason,
            "citations": self.citations
        }
